config/routes.rb
Rails.application.routes.draw do
  root to: 'members#index'
  resources :members, except: [:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/match_concern.rb
module MatchConcern
  extend ActiveSupport::Concern

  included do
    validates :location, :winner_points, :looser_points, presence: true
    validates :winner_points, :looser_points, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 1000 }

    belongs_to :winner, class_name: "Member", foreign_key: "winner_id"
    belongs_to :loser, class_name: "Member", foreign_key: "looser_id"
  end
end

app/models/concerns/member_concern.rb
module MemberConcern
  extend ActiveSupport::Concern

  included do
    CONTACT_NUMBER_REGEX = /\b^([0-9]{10})$\b/
    validates :first_name, :last_name, presence: true
    validates_format_of :contact_number, uniqueness: true,
    :with => CONTACT_NUMBER_REGEX,
    :message => "- Phone numbers must be 10 digits & numbers."
     validates_uniqueness_of :contact_number

    has_many :wins, class_name: "Match", foreign_key: "winner_id"
    has_many :losses, class_name: "Match", foreign_key: "looser_id"
  end
end

app/models/match.rb
class Match < ApplicationRecord
  include ActiveModel::Validations
  validates_with MatchValidator
  include MatchConcern
end

app/models/member.rb
class Member < ApplicationRecord
  include MemberConcern
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update]

  def index
    @leader_boards_members = LeaderboardService.new().call
  end

  def show
    @member_details = MemberProfileService.new(@member).call
  end

  def new
    @member = Member.new
  end

  def edit
  end

  def create
    @member = Member.new(member_params)
    if @member.save
      redirect_to @member, notice: 'Member was successfully created.'
    else
      render :new
    end
  end

  def update
      if @member.update(member_params)
        redirect_to @member, notice: 'Member was successfully updated.'
      else
        render :edit
      end
  end

  private
    def set_member
      @member = Member.find(params[:id])
    end

    def member_params
      params.require(:member).permit(:first_name, :last_name, :contact_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def member_full_name(member)
    "#{member.first_name} #{member.last_name}"    
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ScrabbleClub" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">ScrabbleClub</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Leader Board", root_path, class: 'btn bt-primary'  %></li>
            <li><%= link_to "Create Member", new_member_path, class: 'btn bt-primary'  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="member_form">
    <div class="form-group">
      <label for="first_name">First-name:</label>
      <%= form.text_field :first_name, class: "form-control", required: true %>
    </div>
    <div class="form-group">
      <label for="last_name">Last-name:</label>
      <%= form.text_field :last_name, class: "form-control", required: true %>
    </div>
    <div class="form-group">
      <label for="contact_number">Contact-number:</label>
      <%= form.text_field :contact_number, placeholder: "formate: 10 digits & Number", class: "form-control", required: true %>
    </div>
  </div>

  <%= form.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

app/views/members/index.html.erb
<h3>Leaders Board</h3>

<% if @leader_boards_members.present? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Member Name</th>
        <th>Total Matches</th>
        <th>Average Score</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @leader_boards_members.each do |member| %>
        <tr>
          <td><%= member_full_name(member[:member]) %></td>
          <td><%= member[:total_match] %></td>
          <td><%= member[:average_score] %></td>
          <td><%= link_to 'Show', member[:member] %></td>
          <td><%= link_to 'Edit', edit_member_path(member[:member]) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <strong>No member available that have played at-least 10 matches</strong>
<% end %>

app/views/members/new.html.erb
<h3>Add Member</h3>

<%= render 'form', member: @member %>

app/views/members/show.html.erb
<h3>Member's Profile:</h3>
<h4><strong><%= member_full_name(@member) %></strong></h4>
<br/>
<p>
  <strong>Number of Wins:</strong>
  <%= @member_details[:number_of_wins] %>
</p>

<p>
  <strong>Number of Losses:</strong>
  <%= @member_details[:number_of_losses] %>
</p>

<p>
  <strong>Average Score:</strong>
  <%= @member_details[:average_score] %>
</p>

<p>
  <strong>Highest Score:</strong>
  <% if @member_details[:highest_score].present? %>
    <%= @member_details[:highest_score][:points] %>
    <strong>Played On: </strong>
    <%= @member_details[:highest_score][:date].strftime("%d-%b-%y At %H:%M %p") %>
    <strong>At the Location: </strong>
    <%= @member_details[:highest_score][:location] %>
    <strong>Against: </strong>
    <%= member_full_name(@member_details[:highest_score][:opponent]) %>
  <% else %>
    No Match Played
  <% end %>
</p>